language: ruby

cache:
  bundler: true

rvm:
  - 2.1.2

notifications:
  email:
    - nick.veenhof@acquia.com
    - thomas.meire@acquia.com

script:
  - bundle exec rake fake_dynamo &
  - bundle exec rake test